/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud11;

import javax.swing.JOptionPane;
/**
 *
 * @author nesxr
 */
public class Ejercicio_11 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_11
     */
    public Ejercicio_11() {
        this.setTitle("Burguer Menu APP");
        this.setLocation(1200,600);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHam = new javax.swing.ButtonGroup();
        buttonGroupPan = new javax.swing.ButtonGroup();
        buttonGroupPat = new javax.swing.ButtonGroup();
        buttonGroupBeb = new javax.swing.ButtonGroup();
        buttonGroupRep = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jPanelHam = new javax.swing.JPanel();
        jRadioButtonCerdo = new javax.swing.JRadioButton();
        jRadioButtonPollo = new javax.swing.JRadioButton();
        jRadioButtonTern = new javax.swing.JRadioButton();
        jRadioButtonVeg = new javax.swing.JRadioButton();
        jPanelPan = new javax.swing.JPanel();
        jRadioButtonInt = new javax.swing.JRadioButton();
        jRadioButtonNorm = new javax.swing.JRadioButton();
        jRadioButtonCent = new javax.swing.JRadioButton();
        jPanelPat = new javax.swing.JPanel();
        jRadioButtonCas = new javax.swing.JRadioButton();
        jRadioButtonFrit = new javax.swing.JRadioButton();
        jRadioButtonGaj = new javax.swing.JRadioButton();
        jPanelBeb = new javax.swing.JPanel();
        jRadioButtonCol = new javax.swing.JRadioButton();
        jRadioButtonNar = new javax.swing.JRadioButton();
        jRadioButtonLim = new javax.swing.JRadioButton();
        jRadioButtonAgua = new javax.swing.JRadioButton();
        jRadioButtonCerv = new javax.swing.JRadioButton();
        jPanelExtra = new javax.swing.JPanel();
        jCheckBoxHamDob = new javax.swing.JCheckBox();
        jCheckBoxQueso = new javax.swing.JCheckBox();
        jCheckBoxPat = new javax.swing.JCheckBox();
        jPanelSalsa = new javax.swing.JPanel();
        jSpinnerKetchup = new javax.swing.JSpinner();
        jSpinnerMost = new javax.swing.JSpinner();
        jSpinnerThai = new javax.swing.JSpinner();
        jSpinnerBarb = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonMain = new javax.swing.JButton();
        jRadioButtonDom = new javax.swing.JRadioButton();
        jRadioButtonLoc = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextFieldPrecio = new javax.swing.JFormattedTextField();
        jFormattedTextFieldIva = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPvp = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 700));
        setSize(new java.awt.Dimension(500, 700));

        jPanelHam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHam.setPreferredSize(new java.awt.Dimension(140, 135));

        buttonGroupHam.add(jRadioButtonCerdo);
        jRadioButtonCerdo.setText("Cerdo");

        buttonGroupHam.add(jRadioButtonPollo);
        jRadioButtonPollo.setText("Pollo");

        buttonGroupHam.add(jRadioButtonTern);
        jRadioButtonTern.setText("Ternera (+1€)");

        buttonGroupHam.add(jRadioButtonVeg);
        jRadioButtonVeg.setText("Vegana (+1€)");

        javax.swing.GroupLayout jPanelHamLayout = new javax.swing.GroupLayout(jPanelHam);
        jPanelHam.setLayout(jPanelHamLayout);
        jPanelHamLayout.setHorizontalGroup(
            jPanelHamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPollo)
                    .addComponent(jRadioButtonCerdo)
                    .addComponent(jRadioButtonTern)
                    .addComponent(jRadioButtonVeg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHamLayout.setVerticalGroup(
            jPanelHamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCerdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonVeg)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelPan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPan.setPreferredSize(new java.awt.Dimension(140, 135));

        buttonGroupPan.add(jRadioButtonInt);
        jRadioButtonInt.setText("Integral");

        buttonGroupPan.add(jRadioButtonNorm);
        jRadioButtonNorm.setText("Normal");

        buttonGroupPan.add(jRadioButtonCent);
        jRadioButtonCent.setText("Centeno");

        javax.swing.GroupLayout jPanelPanLayout = new javax.swing.GroupLayout(jPanelPan);
        jPanelPan.setLayout(jPanelPanLayout);
        jPanelPanLayout.setHorizontalGroup(
            jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonInt)
                    .addComponent(jRadioButtonNorm)
                    .addComponent(jRadioButtonCent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPanLayout.setVerticalGroup(
            jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButtonNorm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPat.setPreferredSize(new java.awt.Dimension(140, 135));

        buttonGroupPat.add(jRadioButtonCas);
        jRadioButtonCas.setText("Caseras (+1€)");

        buttonGroupPat.add(jRadioButtonFrit);
        jRadioButtonFrit.setText("Fritas");

        buttonGroupPat.add(jRadioButtonGaj);
        jRadioButtonGaj.setText("Gajo");

        javax.swing.GroupLayout jPanelPatLayout = new javax.swing.GroupLayout(jPanelPat);
        jPanelPat.setLayout(jPanelPatLayout);
        jPanelPatLayout.setHorizontalGroup(
            jPanelPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGaj)
                    .addComponent(jRadioButtonFrit)
                    .addComponent(jRadioButtonCas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPatLayout.setVerticalGroup(
            jPanelPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButtonFrit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBeb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroupBeb.add(jRadioButtonCol);
        jRadioButtonCol.setText("Cola");

        buttonGroupBeb.add(jRadioButtonNar);
        jRadioButtonNar.setText("Naranja");

        buttonGroupBeb.add(jRadioButtonLim);
        jRadioButtonLim.setText("Limón");

        buttonGroupBeb.add(jRadioButtonAgua);
        jRadioButtonAgua.setText("Agua");

        buttonGroupBeb.add(jRadioButtonCerv);
        jRadioButtonCerv.setText("Cerveza");

        javax.swing.GroupLayout jPanelBebLayout = new javax.swing.GroupLayout(jPanelBeb);
        jPanelBeb.setLayout(jPanelBebLayout);
        jPanelBebLayout.setHorizontalGroup(
            jPanelBebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonLim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCerv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBebLayout.setVerticalGroup(
            jPanelBebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelBebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCol)
                    .addComponent(jRadioButtonNar)
                    .addComponent(jRadioButtonLim)
                    .addComponent(jRadioButtonAgua)
                    .addComponent(jRadioButtonCerv))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanelExtra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelExtra.setPreferredSize(new java.awt.Dimension(230, 130));

        jCheckBoxHamDob.setText("Hamburguesa doble (+2€)");

        jCheckBoxQueso.setText("Extra de queso (+0.50€)");

        jCheckBoxPat.setText("Extra de patatas (+1€)");

        javax.swing.GroupLayout jPanelExtraLayout = new javax.swing.GroupLayout(jPanelExtra);
        jPanelExtra.setLayout(jPanelExtraLayout);
        jPanelExtraLayout.setHorizontalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxHamDob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExtraLayout.setVerticalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBoxHamDob)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxQueso)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxPat)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelSalsa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSalsa.setPreferredSize(new java.awt.Dimension(230, 130));

        jLabel1.setText("Barbacoa");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel2.setText("Ketchup");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel3.setText("Mostaza");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel4.setText("Thai");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanelSalsaLayout = new javax.swing.GroupLayout(jPanelSalsa);
        jPanelSalsa.setLayout(jPanelSalsaLayout);
        jPanelSalsaLayout.setHorizontalGroup(
            jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalsaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jSpinnerBarb, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerMost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jSpinnerThai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSalsaLayout.setVerticalGroup(
            jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalsaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMost)
                    .addComponent(jSpinnerKetchup)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerThai)
                    .addComponent(jSpinnerBarb)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jButtonMain.setText("CALCULAR");
        jButtonMain.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainActionPerformed(evt);
            }
        });

        buttonGroupRep.add(jRadioButtonDom);
        jRadioButtonDom.setText("Reparto a domicilio");

        buttonGroupRep.add(jRadioButtonLoc);
        jRadioButtonLoc.setText("Recogida en local (-20% dto)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Hamburguesa");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Pan");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Patatas");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Patatas");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Opciones extra/adicionales");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel10.setText("P.V.P");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Salsas (+0.50€ cada una)");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel12.setText("PRECIO");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel13.setText("IVA (21%)");
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Menú básico (8€):");

        jFormattedTextFieldPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00 €"))));
        jFormattedTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jFormattedTextFieldIva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00 €"))));
        jFormattedTextFieldIva.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jFormattedTextFieldPvp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00 €"))));
        jFormattedTextFieldPvp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelBeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButtonDom)
                    .addComponent(jPanelExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButtonLoc)
                    .addComponent(jPanelSalsa, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelHam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButtonMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(19, 19, 19))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(59, 59, 59))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(209, 209, 209)))
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldPvp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jPanelPan, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jPanelHam, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jPanelSalsa, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainActionPerformed
        // TODO add your handling code here:
        
        double precio = 8;
        double iva;
        double pvp;
        
        //Opciones obligatorias
        //Al menos una hamburguesa
        if (jRadioButtonPollo.isSelected() || jRadioButtonCerdo.isSelected() ||
                jRadioButtonTern.isSelected() || jRadioButtonVeg.isSelected()) {
            if (jRadioButtonTern.isSelected() || jRadioButtonVeg.isSelected()) {
                precio += 1;
            }
        } else {
            JOptionPane.showMessageDialog(this,"Debe elegir un tipo de hamburguesa",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Al menos un tipo de pan
        if (!jRadioButtonNorm.isSelected() && !jRadioButtonInt.isSelected() &&
                !jRadioButtonCent.isSelected()) {
            JOptionPane.showMessageDialog(this,"Debe elegir un tipo de pan",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Al menos un tipo de patatas
        if (jRadioButtonFrit.isSelected() || jRadioButtonGaj.isSelected() ||
                jRadioButtonCas.isSelected()) {
            if (jRadioButtonCas.isSelected()) {
                precio += 1;
            }
        } else {
            JOptionPane.showMessageDialog(this,"Debe elegir un tipo de patatas",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Al menos un tipo de bebida
        if (!jRadioButtonCol.isSelected() && !jRadioButtonNar.isSelected() &&
                !jRadioButtonLim.isSelected() && !jRadioButtonAgua.isSelected() && 
                !jRadioButtonCerv.isSelected()) {
            JOptionPane.showMessageDialog(this,"Debe elegir un tipo de bebida",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Opciones extra/adicionales
        if(jCheckBoxHamDob.isSelected()) {
            precio += 2;
        }
        if(jCheckBoxQueso.isSelected()) {
            precio += 0.5;
        }        
        if(jCheckBoxPat.isSelected()) {
            precio += 1;
        }
        
        //Cantidad de salsa seleccionada
        int cantidadSalsa = (int)jSpinnerKetchup.getValue() + (int)jSpinnerBarb.getValue() +
                            (int)jSpinnerMost.getValue() + (int)jSpinnerThai.getValue();
        precio += (double)cantidadSalsa*0.5;
        
        //Tipo ded reparto
        if(!jRadioButtonDom.isSelected() && jRadioButtonLoc.isSelected()) {
            JOptionPane.showMessageDialog(this,"Debe elegir un tipo de recogida",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        } else if(jRadioButtonLoc.isSelected()) {
            precio *= 0.8;
        }
        
        //Calculadora de precios
        iva = precio * 0.21;
        pvp = precio + iva;
        jFormattedTextFieldPrecio.setValue(precio);
        jFormattedTextFieldIva.setValue(iva);
        jFormattedTextFieldPvp.setValue(pvp);
        
        
    }//GEN-LAST:event_jButtonMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupBeb;
    private javax.swing.ButtonGroup buttonGroupHam;
    private javax.swing.ButtonGroup buttonGroupPan;
    private javax.swing.ButtonGroup buttonGroupPat;
    private javax.swing.ButtonGroup buttonGroupRep;
    private javax.swing.JButton jButtonMain;
    private javax.swing.JCheckBox jCheckBoxHamDob;
    private javax.swing.JCheckBox jCheckBoxPat;
    private javax.swing.JCheckBox jCheckBoxQueso;
    private javax.swing.JFormattedTextField jFormattedTextFieldIva;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecio;
    private javax.swing.JFormattedTextField jFormattedTextFieldPvp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBeb;
    private javax.swing.JPanel jPanelExtra;
    private javax.swing.JPanel jPanelHam;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPan;
    private javax.swing.JPanel jPanelPat;
    private javax.swing.JPanel jPanelSalsa;
    private javax.swing.JRadioButton jRadioButtonAgua;
    private javax.swing.JRadioButton jRadioButtonCas;
    private javax.swing.JRadioButton jRadioButtonCent;
    private javax.swing.JRadioButton jRadioButtonCerdo;
    private javax.swing.JRadioButton jRadioButtonCerv;
    private javax.swing.JRadioButton jRadioButtonCol;
    private javax.swing.JRadioButton jRadioButtonDom;
    private javax.swing.JRadioButton jRadioButtonFrit;
    private javax.swing.JRadioButton jRadioButtonGaj;
    private javax.swing.JRadioButton jRadioButtonInt;
    private javax.swing.JRadioButton jRadioButtonLim;
    private javax.swing.JRadioButton jRadioButtonLoc;
    private javax.swing.JRadioButton jRadioButtonNar;
    private javax.swing.JRadioButton jRadioButtonNorm;
    private javax.swing.JRadioButton jRadioButtonPollo;
    private javax.swing.JRadioButton jRadioButtonTern;
    private javax.swing.JRadioButton jRadioButtonVeg;
    private javax.swing.JSpinner jSpinnerBarb;
    private javax.swing.JSpinner jSpinnerKetchup;
    private javax.swing.JSpinner jSpinnerMost;
    private javax.swing.JSpinner jSpinnerThai;
    // End of variables declaration//GEN-END:variables
}
